name = "snapshot2"
main = "src/index.ts"
compatibility_date = "2023-05-28"
node_compat = true
workers_dev = true

browser = { binding = "MYBROWSER", type = "browser" }
kv_namespaces = [
  { binding = "SNAPSHOT", id = "fc654ecac84143cca1ac69d202ccf0a5", preview_id = "fc654ecac84143cca1ac69d202ccf0a5" }
]