-- Migration number: 0002 	 2023-06-05T12:57:36.320Z
ALTER TABLE projectImages ADD COLUMN isLatest INTEGER DEFAULT 0;
ALTER TABLE projectImages ADD COLUMN isBaseline INTEGER DEFAULT 0;
ALTER TABLE projectImages ADD COLUMN isPreview INTEGER DEFAULT 0;
